/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package final1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    //eleman varsa true dönder. doğru sonuç
    public void testfound(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1,2,3,4));
        assertTrue(App.search(array, 4));
    }
    //eleman yoksa false dönder. yanlış sonuç
    public void testNotfound(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1,2,3,4));
        assertFalse(App.search(array, 5));
    }
    //array boş
    public void testemptyArray(){
        ArrayList<Integer> array = new ArrayList<>();
        assertFalse(App.search(array, 5));
    }
    //array hiç oluştuurlmaz ise
    public void testNull(){
        assertFalse(App.search(null, 5));
    }
}
